### ISSUE TITLE
lingfeats.pkl

### ISSUE THREAD

**Issue by e-hossam96** [KevinIoi/truth-finder#1]
Hello KevinIoi,

Thanks for the efforts put into this repository. Yet, the code to generate the `lingfeats.pkl` file seems to be missing. I would really appreciate your help in how to generate it or where to find it in case of working on another dataset.

Thanks

**Comment by kevinioi** [comment]
Hey @E-Hossam96, thanks for taking interest in this project!

The linguistic features file is the index file for a one-hot-encoded corpus of words, which I manually assembled to best approximate what was used for the original [research paper](https://resources.mpi-inf.mpg.de/impact/web_credibility_analysis/www2017_popat.pdf). As outlined in the paper the corpus contains assertive verbs, hedges, implicatives, report verbs and discourse markers. 

If you are using an English language dataset, You could reuse my corpus to train a new model. If this corpus is not suitable for the domain you are targeting, you could compile a new corpus of words from the aforementioned parts of speech and one-hot-encode it to pass to the model.

It is more important to have a customized 'stance' feature set, which is generated by pointing the `createFeatureFile()` function in [utils.featureBag.py](https://github.com/KevinIoi/truth-finder/blob/master/util/featureBag.py), to a directory or relevant text files.

**Comment by e-hossam96** [comment]
Thanks for the clarification.
